### ISSUE TITLE
s/ethereumproject/ethereumclassic/

### ISSUE THREAD

**Issue by mikeyb** [ethereumclassic/go-ethereum#1]
https://github.com/ethereumclassic/go-ethereum/search?q=ethereumproject&unscoped_q=ethereumproject

**Comment by tzdybal** [comment]
I'm working on this.

**Comment by whilei** [comment]
Me too ;)

**Comment by lostinblue** [comment]
Don't go reinventing unnecessary wheels: https://github.com/rogpeppe/govers

**Comment by whatisgravity** [comment]
Its called sed and grep and the fact that you dont know how to do this in literally 5 minutes, shows A LOT about your talent was a computer programmer. Basically you have none.
