### ISSUE TITLE
deploy artifacts for all available tools

### ISSUE THREAD

**Issue by whilei** [ethereumclassic/go-ethereum#15]
Currently we're tentatively only deploying a `geth` executable in the dist archive (ala https://github.com/ethereumclassic/go-ethereum/pull/12/files#diff-1d37e48f9ceff6d8030570cd36286a61R48).

A next step would be to provide an artifact with all available cmds
- https://github.com/ethereumclassic/go-ethereum#executables 
- https://github.com/ethereumclassic/go-ethereum/tree/master/cmd

Rel https://github.com/ethoxy/multi-geth/pull/18/files

**Comment by lostinblue** [comment]
I'm almost sure I fixed this in the other branch, but since I was asked to look here, I will fix this and report back if its something that comes up.
