### ISSUE TITLE
# ⛔️ WARNING ⛔️ : http://github.com/ethereumclassic/ECIPS IS UNOFFICIAL AND SHOULD NOT BE USED.

### ISSUE THREAD

**Issue by whatisgravity** [ethereumclassic/go-ethereum#59]
# ⛔️ WARNING ⛔️ : http://github.com/ethereumclassic/ECIPS IS UNOFFICIAL AND SHOULD NOT BE USED.

ACTUAL development, not just changing names, will be happening under the group https://github.com/openether 

Everyone is welcome to join and participate in an actual decentralized development of the ETC project.

**Comment by soc1c** [comment]
define "official" in a permissionless system :)
